apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-dev-k8s-packages
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: main
    path: infra/clusters/compositions/aws
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
