apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: {{ $.Values.pipelineName }}
  namespace: {{ $.Values.namespace }}
spec:
  description: |
    This pipeline clones a git repo, then echoes the README file to the stout.
  params:
  - name: repo-url
    type: string 
    description: The git repo URL to clone from.
  - name: revision
    type: string
  - name: PARAM_SCM
    description: Define the Source code Management URL
    type: string
    default: "github.com"    
  - name: pathToContext
    description: The path to the build context, used by Kaniko - within the workspace
    default: .
  - name: imageUrl
    description: Image name including repository
  - name: imageTag
    description: Image tag
    default: "latest"
  - name: eventname
    description: name of event happens
  - name: reponame
    description: repo name
  - name: retag
    description: rel tag
 
  workspaces:
  - name: shared-data
    description: |
      This workspace contains the cloned repo files, so they can be read by the
      next task.
  - name: git-credentials
    description: basic-auth
  - name: docker-credentials
    description: docker cred
  - name: cosign
  - name: dockerconfig
  - name: cosign-pub
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-data
    - name: basic-auth
      workspace: git-credentials
    params:
    - name: url
      value: $(params.repo-url)
    - name: PARAM_SCM
      value: $(params.PARAM_SCM)
    - name: revision
      value: $(params.revision)
  - name: build
    taskRef:
      name: kaniko-build
      kind: ClusterTask
    runAfter:
      - fetch-source
    workspaces:
      - name: source
        workspace: shared-data
      - name: dockerconfig
        workspace: docker-credentials
    params:
      - name: CONTEXT
        value: $(params.pathToContext)
      - name: IMAGE
        value: $(params.imageUrl):$(params.imageTag)

  - name: cosign-sign
    runAfter: ["build"]
    taskRef:
      name: cosign-sign
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig
    - name: cosign
      workspace: cosign
    params:
    - name: image
      value: "$(params.imageUrl)@$(tasks.build.results.IMAGE_DIGEST)"
    - name: eventname
      value: "$(params.eventname)"
    when:
    - input: "$(params.eventname)"
      operator: in
      values: [ "push" , "tag" ,"release" ]
  - name: cosign-image-verify
    runAfter: ["cosign-sign"]
    taskRef:
      name: cosign-image-verify
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: shared-data
    - name: dockerconfig
      workspace: dockerconfig
    - name: cosign
      workspace: cosign-pub
    params:
    - name: image
      value: "$(params.imageUrl)@$(tasks.build.results.IMAGE_DIGEST)"
    - name: eventname
      value: "$(params.eventname)"
    when:
    - input: "$(params.eventname)"
      operator: in
      values: [ "push" , "tag" , "release" ]

  finally:
    - name: github-set-status-fail
      when:
      - input: $(tasks.status)
        operator: in
        values: [ "Failed", "None" ] 
      taskRef:
        name: github-set-status
        kind: ClusterTask
      params:
        - name: "STATE"
          value: "failed"
        - name: "GITHUB_HOST_URL"
          value: "api.github.com"
        - name: "REPO_FULL_NAME"
          value: "$(params.reponame)"
        - name: "GITHUB_TOKEN_SECRET_NAME"
          value: "gitcred"
        - name: "GITHUB_TOKEN_SECRET_KEY"
          value: "token"
        - name: "SHA"
          value: "$(params.revision)"
        - name: "TARGET_URL"
          value: {{ $.Values.tektonDashboard }}
          #value: "dashboard.domain.app"
        - name: "CONTEXT"
          value: "tekton-pipeline"
        - name: "DESCRIPTION"
          value: "An error occurred building your commit in Tekton"

    - name: github-set-status-success
      when:
      - input: $(tasks.status)
        operator: in
        values: [ "Succeeded", "Completed" ] 
      taskRef:
        name: github-set-status
        kind: ClusterTask
      params:
        - name: "STATE"
          value: "success"
        - name: "GITHUB_HOST_URL"
          value: "api.github.com"
        - name: "REPO_FULL_NAME"
          value: "$(params.reponame)"
        - name: "GITHUB_TOKEN_SECRET_NAME"
          value: "gitcred"
        - name: "GITHUB_TOKEN_SECRET_KEY"
          value: "token"
        - name: "SHA"
          value: "$(params.revision)"
        - name: "TARGET_URL"
          value: {{ $.Values.tektonDashboard }}
          #value: "dashboard.domain.app"
        - name: "CONTEXT"
          value: "tekton-pipeline"
        - name: "DESCRIPTION"
          value: "Finished building your commit in Tekton"
    





 




