apiVersion: kubernetes.do.crossplane.io/v1alpha1
kind: DOKubernetesCluster
metadata:
  name: digitalocean-cluster
spec:
  providerConfigRef:
    name: digitalocean-provider
  forProvider:
    region: nyc1
    version: 1.21.5-do.0
    tags:
      - example-tag
    nodePools:
      - size: s-1vcpu-2gb
        count: 1
        name: worker-pool
    maintenancePolicy:
      startTime: "00:00"
      day: wednesday
    autoUpgrade: true
    surgeUpgrade: false
    highlyAvailable: false
