apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extraconfig-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: ClusterSecretStore
  target:
    name: extraconfig-capten-pipeline
  data:
  - secretKey: GIT_TOKEN
    remoteRef:
      key: generic/git-project/fa7f13c6-16b7-42de-8ecd-077be81a017d
      property: accessToken
  - secretKey: GIT_USER_NAME
    remoteRef:
      key: generic/git-project/fa7f13c6-16b7-42de-8ecd-077be81a017d
      property: userID

