apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    tekton.dev/git-0: https://gitlab.com
  name: gitcred-external
  namespace: tekton-pipelines
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: SecretStore
  target:
    name: gitcred-capten-pipeline-gitlab
  data:
  - secretKey: password
    remoteRef:
      key: generic/git-project/d2d36daf-ff1c-4dea-bfd8-a8e5e9524527
      property: accessToken
  - secretKey: username
    remoteRef:
      key: generic/git-project/d2d36daf-ff1c-4dea-bfd8-a8e5e9524527
      property: userID
