apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/indresh-28/test-tekton.git
    targetRevision: main
    path: infra/crossplane/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane