prometheus:
  prometheusSpec:
     externalLabels: 
      cluster_name: clustername
     enableRemoteWriteReceiver: true
     externalUrl: "https://prometheus.app/api/v1/write"

alertmanager:
  enabled: false
  
grafana:
  enabled: false
  
kubeStateMetrics:
  enabled: false
  
nodeExporter:
  enabled: false
  
  

