apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: cosign-sign
spec:
  workspaces:
    - name: source
    - name: dockerconfig
      description: "An optional workspace that allows providing a .docker/config.json file for Buildah to access the container registry. The file should be placed at the root of the Workspace with name config.json."
      optional: true
    - name: cosign
      description: "Cosign private key to sign image"
  params:
    - name: image
      description: "The image to be signed by cosign."
      type: string
    # - name: COSIGN_RELEASE
    #   description: "The cosign release version to install."
    #   type: string
  steps:
    - name: cosign-sign
      image: ghcr.io/kube-tarian/helmrepo-supporting-tools/cosign:2.1.1
      script: |
        mkdir -p ~/.docker/
        export registry=`cat /workspace/dockerconfig/registry`
        export username=`cat /workspace/dockerconfig/username`
        export password=`cat /workspace/dockerconfig/password`
        cosign login $registry -u $username -p $password
        export COSIGN_PASSWORD=""
        cosign sign -y --key /workspace/cosign/cosign.key $(params.image)
      securityContext:
        privileged: false
