apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-dev-cluster
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: main
    path: infra/crossplane/clusters/dev/clusterconfigs
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
