apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-provider
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/intelops/capten-templates.git
    targetRevision: main
    path: infra/crossplane/crossplane-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
