apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.azureagent.optimizor.app"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-root-token"
          key: "token"
          namespace: kyverno
