apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.pipelineName }}
  namespace: {{ $.Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: "tekton.{{ $.Values.ingressDomainName }}"
      http:
        paths:
          - path: "/{{ $.Values.pipelineName }}"
            pathType: Prefix
            backend:
              service:
                name: "el-{{ $.Values.pipelineName }}"
                port:
                  number: 8080
