apiVersion: v1
kind: ServiceAccount
metadata:
  name: capten-pipeline
  namespace: tekton-pipelines

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capten-pipeline
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources: ["*"]
  verbs: ["get", "list", "watch" , "update" , "create"]
- apiGroups: ["tekton.dev"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capten-pipeline
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: capten-pipeline
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: capten-pipeline
