apiVersion: v2
version: 1.1.5
appVersion: v1.1.3
name: agent
description: kubviz-agent Helm chart for Kubernetes
dependencies:
  - name: agent
    version: 1.1.5
    repository: https://kube-tarian.github.io/helmrepo-supporting-tools
