apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcrd-docker
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: vault-root-store
    kind: ClusterSecretStore
  target:
    name: ghcrd-docker
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: secret/generic/container-registry/8b8c0091-a3fa-4441-a7b3-90346e1618a2
      property: config.json

