apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-root-store
spec:
  provider:
    vault:
      server: "http://vault.aws.optimizor.app"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "tekton-vault-token"
          key: "token"
          namespace: tekton
