apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: cosign-sign
spec:
  workspaces:
    - name: source
    - name: dockerconfig
      description: "An optional workspace that allows providing a .docker/config.json file for Buildah to access the container registry. The file should be placed at the root of the Workspace with name config.json."
      optional: true
    - name: cosign
      description: "Cosign private key to sign image"
  params:
    - name: image
      description: "The image to be signed by cosign."
      type: string
    - name: registry
      description: "registry"
      type: string
    
  steps:
    - name: cosign-sign
      image: ghcr.io/kube-tarian/helmrepo-supporting-tools/cosign:v2.2.2
      resources:
        limits:
          cpu: 200m
          memory: 300Mi
        requests:
          cpu: 3m
          memory: 20Mi
      script: |
        #!/usr/bin/env bash
        mkdir -p ~/.docker/
        export username=`cat /workspace/dockerconfig/username`
        export password=`cat /workspace/dockerconfig/password`
        cosign login $(params.registry) -u $username -p $password
        export COSIGN_PASSWORD=""
        cosign sign -y --key /workspace/cosign/cosign.key $(params.image)
      securityContext:
        privileged: false
