apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: get-changed-files-task
spec:
  params:
    - name: REVISION
      description: Git revision to check
      type: string
  steps:
    - name: get-changed-files
      image: ghcr.io/kube-tarian/helmrepo-supporting-tools/build1:latest
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 50m
          memory: 30Mi
      script: |
        #!/bin/sh
        git config --global --add safe.directory /workspace/source
        git checkout $(params.REVISION)
        ls
        commit_email=$(git show -s --format='%ae' $(params.REVISION))
        echo -n "$commit_email"
        echo -n "$commit_email" > "$(results.email.path)"
        file_list=$(git diff-tree --no-commit-id --name-only -r $(params.REVISION)) 
        file_new=$(git diff-tree --no-commit-id --name-only -r $(params.REVISION) | sed 's@/.*@@' | sort -u)
        echo "Files in commit $(params.REVISION):"
        echo "$file_list"
        echo "$file_new"
        echo -n "$file_list" > "$(results.changed-files.path)"
        echo -n "$file_new" > "$(results.changed-dir.path)"
      workingDir: $(workspaces.source.path)
  results:
    - name: changed-files
      description: "List of changed files"
    - name: changed-dir
      description: "List of changed files"
    - name: email
      description: "email"
  workspaces:
    - name: source
      description: Holds the context and Dockerfile



